version: "3.7"

services:
    webapp:
        build: .
        container_name: django-crypto
        volumes:
            - .:/django-crontab
        env_file: .env
        ports:
            - 8000:8000